# Generated by Django 5.2.10 on 2026-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.JSONField(
                blank=True, help_text="Raw response from payment gateway", null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("mobile", "Mobile Payment"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("sslcommerz", "SSLCommerz"),
                    ("stripe", "Stripe"),
                    ("other", "Other"),
                ],
                default="card",
                max_length=20,
            ),
        ),
    ]
