# Generated by Django 4.2.30 on 2026-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_case_nullable_invoice"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "-issue_date"], name="payments_in_client__bc61ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="payments_in_status_68daea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["client", "-created_at"], name="payments_pa_client__ef8bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_21ed42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status"], name="payments_pa_invoice_e2429a_idx"
            ),
        ),
    ]
