# Generated by Django 4.2.30 on 2026-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_client_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["client", "-created_at"], name="cases_case_client__933763_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["lawyer", "-created_at"], name="cases_case_lawyer__73fad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["status", "-created_at"], name="cases_case_status_f8be30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["case", "-created_at"], name="cases_cased_case_id_d5d10c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casetimeline",
            index=models.Index(
                fields=["case", "-date"], name="cases_caset_case_id_c6e38f_idx"
            ),
        ),
    ]
