# Generated by Django 4.2.30 on 2026-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["client", "-date_time"], name="appointment_client__eafc3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["lawyer", "-date_time"], name="appointment_lawyer__060834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "-date_time"], name="appointment_status_649aa0_idx"
            ),
        ),
    ]
