# Generated by Django 5.2.10 on 2026-01-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon_name", models.CharField(blank=True, max_length=50)),
                ("detailed_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Practice Area",
                "verbose_name_plural": "Practice Areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LawyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("solved_cases", models.PositiveIntegerField(default=0)),
                (
                    "consultancy_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("qualifications", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("chamber_info", models.TextField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lawyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practice_areas",
                    models.ManyToManyField(
                        blank=True, related_name="lawyers", to="lawyers.practicearea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lawyer Profile",
                "verbose_name_plural": "Lawyer Profiles",
                "ordering": ["-rating", "-years_experience"],
            },
        ),
        migrations.CreateModel(
            name="LawyerAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lawyer Availability",
                "verbose_name_plural": "Lawyer Availabilities",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("lawyer", "day_of_week", "start_time")},
            },
        ),
    ]
