# Generated by Django 5.2.10 on 2026-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="profession",
            field=models.CharField(blank=True, default="Lawyer", max_length=100),
        ),
    ]
