# Generated by Django 5.2.10 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0002_lawyerprofile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="specialization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
