# Generated by Django 5.2.10 on 2026-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0003_lawyerprofile_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=10,
            ),
        ),
    ]
