# Generated by Django 5.2.10 on 2026-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0004_lawyerprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="district",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="location",
            field=models.CharField(db_index=True, default="", max_length=150),
        ),
    ]
